# Generated by Django 5.2.1 on 2025-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.CharField(choices=[('like', '👍 Лайк'), ('dislike', '👎 Дизлайк')], max_length=7),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
    ]
