# Generated by Django 5.2.1 on 2025-05-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_watchlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(max_length=255),
        ),
    ]
