# Generated by Django 5.2.1 on 2025-05-29 11:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rating_is_favorite_alter_rating_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewlog',
            unique_together={('user', 'video')},
        ),
    ]
