# Generated by Django 5.2.1 on 2025-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_viewlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
